services:
  app:
    build: ./
    volumes:
      - .:/back
    restart: always
    command: php artisan serve --host 0.0.0.0
  worker:
    build: ./
    volumes:
      - .:/back
    restart: always
    command: php artisan queue:work --verbose
  web:
    image: nginx
    ports:
      - "8081:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt:ro
      - ./nginx.key:/etc/nginx/ssl/nginx.key:ro
    restart: always
